# ---------------------------------------------------------------------------
#  make                build the server and the client into bin/
#  make test           build + run unit tests and end-to-end tests
#  make SAN=1 test     same, with AddressSanitizer + UndefinedBehaviorSanitizer
#  make microbench     run the data-structure micro benchmarks
#  make benchmark      compare with real Redis using redis-benchmark
#  make clean
# ---------------------------------------------------------------------------

CXX      := g++
CXXFLAGS := -std=c++17 -Wall -Wextra -g -MMD -MP
LDFLAGS  :=

ifeq ($(SAN),1)
  # Sanitizers add runtime checks for memory errors and undefined behaviour.
  CXXFLAGS += -O1 -fsanitize=address,undefined -fno-omit-frame-pointer
  LDFLAGS  += -fsanitize=address,undefined
  BUILD    := build/san
  BIN      := bin/san
else
  CXXFLAGS += -O2
  BUILD    := build/release
  BIN      := bin
endif

# All server code except main.cpp is shared with the unit tests and benchmarks.
CORE_SRCS   := $(filter-out server/main.cpp,$(wildcard server/*.cpp))
CLIENT_SRCS := $(wildcard client/*.cpp)
TEST_SRCS   := $(wildcard tests/*.cpp)

CORE_OBJS   := $(CORE_SRCS:%.cpp=$(BUILD)/%.o)
CLIENT_OBJS := $(CLIENT_SRCS:%.cpp=$(BUILD)/%.o)
TEST_OBJS   := $(TEST_SRCS:%.cpp=$(BUILD)/%.o)

SERVER_BIN := $(BIN)/mini-redis-server
CLIENT_BIN := $(BIN)/mini-redis-cli
TEST_BIN   := $(BIN)/unit-tests
BENCH_BIN  := $(BIN)/micro-bench

.PHONY: all test unit-test e2e-test microbench benchmark clean

all: $(SERVER_BIN) $(CLIENT_BIN)

$(SERVER_BIN): $(CORE_OBJS) $(BUILD)/server/main.o
	@mkdir -p $(dir $@)
	$(CXX) $^ -o $@ $(LDFLAGS)

$(CLIENT_BIN): $(CLIENT_OBJS)
	@mkdir -p $(dir $@)
	$(CXX) $^ -o $@ $(LDFLAGS)

$(TEST_BIN): $(CORE_OBJS) $(TEST_OBJS)
	@mkdir -p $(dir $@)
	$(CXX) $^ -o $@ $(LDFLAGS)

$(BENCH_BIN): $(CORE_OBJS) $(BUILD)/bench/micro_bench.o
	@mkdir -p $(dir $@)
	$(CXX) $^ -o $@ $(LDFLAGS)

# Compile any .cpp into build/<config>/<same path>.o
$(BUILD)/%.o: %.cpp
	@mkdir -p $(dir $@)
	$(CXX) $(CXXFLAGS) -c $< -o $@

test: unit-test e2e-test

unit-test: $(TEST_BIN)
	./$(TEST_BIN)

e2e-test: all
	BIN_DIR=$(BIN) bash tests/e2e_test.sh

microbench: $(BENCH_BIN)
	./$(BENCH_BIN)

benchmark: all
	BIN_DIR=$(BIN) bash bench/run_benchmarks.sh

clean:
	rm -rf build bin

# Header dependency files generated by -MMD (rebuild when a header changes).
-include $(wildcard $(BUILD)/*/*.d)
